#!/usr/bin/env bash

set -o errexit    # always exit on error
set -o pipefail   # don't ignore exit codes when piping output
set -o nounset    # fail on unset variables

if [ ! -d "all-the-packages" ]; then
  git clone https://github.com/zeke/all-the-packages
fi

cd all-the-packages
npm run build
npm test

status=$(git status skimdb.json.tgz 2>&1)

if [[ "$status" =~ "modified:" ]]; then
  count=$(cat names.json | wc -l)
  echo "$count package names!"
  git add names.json
  git config user.email "zeke@sikelianos.com"
  git config user.name "Zeke Sikelianos"
  git commit -m "$count package names"
  npm version minor -m "bump minor to %s"
  npm publish
  git push origin master --follow-tags
fi
